//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Matchmaker.Http;



namespace Unity.Services.Matchmaker.Models
{
    /// <summary>
    /// CustomConnectionDetails model
    /// </summary>
    [Preserve]
    [DataContract(Name = "CustomConnectionDetails")]
    public class CustomConnectionDetails
    {
        /// <summary>
        /// Creates an instance of CustomConnectionDetails.
        /// </summary>
        /// <param name="type">type param</param>
        /// <param name="customData">customData param</param>
        [Preserve]
        public CustomConnectionDetails(string type, Dictionary<string, object> customData = default)
        {
            Type = type;
            CustomData = (Dictionary<string, IDeserializable>) JsonObject.GetNewJsonObjectResponse(customData);
        }

        /// <summary>
        /// Parameter type of CustomConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type{ get; }

        /// <summary>
        /// Parameter customData of CustomConnectionDetails
        /// </summary>
        [Preserve][JsonConverter(typeof(JsonObjectCollectionConverter))]
        [DataMember(Name = "customData", EmitDefaultValue = false)]
        public Dictionary<string, IDeserializable> CustomData{ get; }

        /// <summary>
        /// Formats a CustomConnectionDetails into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Type != null)
            {
                serializedModel += "type," + Type + ",";
            }
            if (CustomData != null)
            {
                serializedModel += "customData," + CustomData.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a CustomConnectionDetails as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Type != null)
            {
                var typeStringValue = Type.ToString();
                dictionary.Add("type", typeStringValue);
            }

            if (CustomData != null)
            {
                var customDataStringValue = CustomData.ToString();
                dictionary.Add("customData", customDataStringValue);
            }

            return dictionary;
        }
    }
}
