//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Matchmaker.Http;



namespace Unity.Services.Matchmaker.Models
{
    /// <summary>
    /// IpPortConnectionDetails model
    /// </summary>
    [Preserve]
    [DataContract(Name = "IpPortConnectionDetails")]
    public class IpPortConnectionDetails
    {
        /// <summary>
        /// Creates an instance of IpPortConnectionDetails.
        /// </summary>
        /// <param name="type">type param</param>
        /// <param name="ip">ip param</param>
        /// <param name="port">port param</param>
        /// <param name="customData">customData param</param>
        [Preserve]
        public IpPortConnectionDetails(string type, string ip = default, int port = default, Dictionary<string, object> customData = default)
        {
            Type = type;
            Ip = ip;
            Port = port;
            CustomData = (Dictionary<string, IDeserializable>) JsonObject.GetNewJsonObjectResponse(customData);
        }

        /// <summary>
        /// Parameter type of IpPortConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type{ get; }

        /// <summary>
        /// Parameter ip of IpPortConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip{ get; }

        /// <summary>
        /// Parameter port of IpPortConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "port", EmitDefaultValue = false)]
        public int Port{ get; }

        /// <summary>
        /// Parameter customData of IpPortConnectionDetails
        /// </summary>
        [Preserve][JsonConverter(typeof(JsonObjectCollectionConverter))]
        [DataMember(Name = "customData", EmitDefaultValue = false)]
        public Dictionary<string, IDeserializable> CustomData{ get; }

        /// <summary>
        /// Formats a IpPortConnectionDetails into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Type != null)
            {
                serializedModel += "type," + Type + ",";
            }
            if (Ip != null)
            {
                serializedModel += "ip," + Ip + ",";
            }
            serializedModel += "port," + Port.ToString() + ",";
            if (CustomData != null)
            {
                serializedModel += "customData," + CustomData.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a IpPortConnectionDetails as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Type != null)
            {
                var typeStringValue = Type.ToString();
                dictionary.Add("type", typeStringValue);
            }

            if (Ip != null)
            {
                var ipStringValue = Ip.ToString();
                dictionary.Add("ip", ipStringValue);
            }

            var portStringValue = Port.ToString();
            dictionary.Add("port", portStringValue);

            if (CustomData != null)
            {
                var customDataStringValue = CustomData.ToString();
                dictionary.Add("customData", customDataStringValue);
            }

            return dictionary;
        }
    }
}
