//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Matchmaker.Http;



namespace Unity.Services.Matchmaker.Models
{
    /// <summary>
    /// MultiplayConnectionDetails model
    /// </summary>
    [Preserve]
    [DataContract(Name = "MultiplayConnectionDetails")]
    public class MultiplayConnectionDetails
    {
        /// <summary>
        /// Creates an instance of MultiplayConnectionDetails.
        /// </summary>
        /// <param name="type">type param</param>
        /// <param name="ip">ip param</param>
        /// <param name="port">port param</param>
        [Preserve]
        public MultiplayConnectionDetails(string type, string ip = default, int port = default)
        {
            Type = type;
            Ip = ip;
            Port = port;
        }

        /// <summary>
        /// Parameter type of MultiplayConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type{ get; }
        
        /// <summary>
        /// Parameter ip of MultiplayConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip{ get; }
        
        /// <summary>
        /// Parameter port of MultiplayConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "port", EmitDefaultValue = false)]
        public int Port{ get; }
    
        /// <summary>
        /// Formats a MultiplayConnectionDetails into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Type != null)
            {
                serializedModel += "type," + Type + ",";
            }
            if (Ip != null)
            {
                serializedModel += "ip," + Ip + ",";
            }
            serializedModel += "port," + Port.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a MultiplayConnectionDetails as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Type != null)
            {
                var typeStringValue = Type.ToString();
                dictionary.Add("type", typeStringValue);
            }
            
            if (Ip != null)
            {
                var ipStringValue = Ip.ToString();
                dictionary.Add("ip", ipStringValue);
            }
            
            var portStringValue = Port.ToString();
            dictionary.Add("port", portStringValue);
            
            return dictionary;
        }
    }
}
