//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Matchmaker.Http;



namespace Unity.Services.Matchmaker.Models
{
    /// <summary>
    /// Assignment type used when the final type is not yet determined (e.g., CloudCode hosting before allocation completes) or for allocation errors. Contains only status information - no connection data.
    /// </summary>
    [Preserve]
    [DataContract(Name = "NoneAssignment")]
    public class NoneAssignment
    {
        /// <summary>
        /// Assignment type used when the final type is not yet determined (e.g., CloudCode hosting before allocation completes) or for allocation errors. Contains only status information - no connection data.
        /// </summary>
        /// <param name="assignmentType">assignmentType param</param>
        /// <param name="message">Error details when status is &#39;Failed&#39;. Common values include &#39;Allocation error: &lt;details&gt;&#39; or &#39;AllocationError&#39;.</param>
        /// <param name="status">The status of the assignment is one of Timeout, Failed, InProgress, Found</param>
        [Preserve]
        public NoneAssignment(string assignmentType, string message = default, StatusOptions status = default)
        {
            AssignmentType = assignmentType;
            Message = message;
            Status = status;
        }

        /// <summary>
        /// Parameter assignmentType of NoneAssignment
        /// </summary>
        [Preserve]
        [DataMember(Name = "assignmentType", IsRequired = true, EmitDefaultValue = true)]
        public string AssignmentType{ get; }
        
        /// <summary>
        /// Error details when status is &#39;Failed&#39;. Common values include &#39;Allocation error: &lt;details&gt;&#39; or &#39;AllocationError&#39;.
        /// </summary>
        [Preserve]
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message{ get; }
        
        /// <summary>
        /// The status of the assignment is one of Timeout, Failed, InProgress, Found
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusOptions Status{ get; }
    
        /// <summary>
        /// The status of the assignment is one of Timeout, Failed, InProgress, Found
        /// </summary>
        /// <value>The status of the assignment is one of Timeout, Failed, InProgress, Found</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusOptions
        {
            /// <summary>
            /// Enum Timeout for value: Timeout
            /// </summary>
            [EnumMember(Value = "Timeout")]
            Timeout = 1,
            /// <summary>
            /// Enum Failed for value: Failed
            /// </summary>
            [EnumMember(Value = "Failed")]
            Failed = 2,
            /// <summary>
            /// Enum InProgress for value: InProgress
            /// </summary>
            [EnumMember(Value = "InProgress")]
            InProgress = 3,
            /// <summary>
            /// Enum Found for value: Found
            /// </summary>
            [EnumMember(Value = "Found")]
            Found = 4
        }

        /// <summary>
        /// Formats a NoneAssignment into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (AssignmentType != null)
            {
                serializedModel += "assignmentType," + AssignmentType + ",";
            }
            if (Message != null)
            {
                serializedModel += "message," + Message + ",";
            }
            serializedModel += "status," + Status;
            return serializedModel;
        }

        /// <summary>
        /// Returns a NoneAssignment as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (AssignmentType != null)
            {
                var assignmentTypeStringValue = AssignmentType.ToString();
                dictionary.Add("assignmentType", assignmentTypeStringValue);
            }
            
            if (Message != null)
            {
                var messageStringValue = Message.ToString();
                dictionary.Add("message", messageStringValue);
            }
            
            var statusStringValue = Status.ToString();
            dictionary.Add("status", statusStringValue);
            
            return dictionary;
        }
    }
}
