//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Matchmaker.Http;



namespace Unity.Services.Matchmaker.Models
{
    /// <summary>
    /// RelayConnectionDetails model
    /// </summary>
    [Preserve]
    [DataContract(Name = "RelayConnectionDetails")]
    public class RelayConnectionDetails
    {
        /// <summary>
        /// Creates an instance of RelayConnectionDetails.
        /// </summary>
        /// <param name="type">type param</param>
        /// <param name="joinCode">joinCode param</param>
        [Preserve]
        public RelayConnectionDetails(string type, string joinCode = default)
        {
            Type = type;
            JoinCode = joinCode;
        }

        /// <summary>
        /// Parameter type of RelayConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type{ get; }
        
        /// <summary>
        /// Parameter joinCode of RelayConnectionDetails
        /// </summary>
        [Preserve]
        [DataMember(Name = "joinCode", EmitDefaultValue = false)]
        public string JoinCode{ get; }
    
        /// <summary>
        /// Formats a RelayConnectionDetails into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Type != null)
            {
                serializedModel += "type," + Type + ",";
            }
            if (JoinCode != null)
            {
                serializedModel += "joinCode," + JoinCode;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a RelayConnectionDetails as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Type != null)
            {
                var typeStringValue = Type.ToString();
                dictionary.Add("type", typeStringValue);
            }
            
            if (JoinCode != null)
            {
                var joinCodeStringValue = JoinCode.ToString();
                dictionary.Add("joinCode", joinCodeStringValue);
            }
            
            return dictionary;
        }
    }
}
