//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Lobbies.Http;



namespace Unity.Services.Lobbies.Models
{
    /// <summary>
    /// The migration data information of a lobby.
    /// </summary>
    [Preserve]
    [DataContract(Name = "MigrationDataInfo")]
    public class MigrationDataInfo
    {
        /// <summary>
        /// The migration data information of a lobby.
        /// </summary>
        /// <param name="write">The migration data write url.</param>
        /// <param name="read">The migration data read url.</param>
        /// <param name="expires">When the urls will expire. The timestamp is in UTC and conforms to ISO 8601.</param>
        /// <param name="maxSize">The max size of migration data in bytes.</param>
        [Preserve]
        public MigrationDataInfo(string write = default, string read = default, DateTime expires = default, int maxSize = default)
        {
            Write = write;
            Read = read;
            Expires = expires;
            MaxSize = maxSize;
        }

        /// <summary>
        /// The migration data write url.
        /// </summary>
        [Preserve]
        [DataMember(Name = "write", EmitDefaultValue = false)]
        public string Write{ get; }
        
        /// <summary>
        /// The migration data read url.
        /// </summary>
        [Preserve]
        [DataMember(Name = "read", EmitDefaultValue = false)]
        public string Read{ get; }
        
        /// <summary>
        /// When the urls will expire. The timestamp is in UTC and conforms to ISO 8601.
        /// </summary>
        [Preserve]
        [DataMember(Name = "expires", EmitDefaultValue = false)]
        public DateTime Expires{ get; }
        
        /// <summary>
        /// The max size of migration data in bytes.
        /// </summary>
        [Preserve]
        [DataMember(Name = "maxSize", EmitDefaultValue = false)]
        public int MaxSize{ get; }
    
        /// <summary>
        /// Formats a MigrationDataInfo into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Write != null)
            {
                serializedModel += "write," + Write + ",";
            }
            if (Read != null)
            {
                serializedModel += "read," + Read + ",";
            }
            if (Expires != null)
            {
                serializedModel += "expires," + Expires.ToString() + ",";
            }
            serializedModel += "maxSize," + MaxSize.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a MigrationDataInfo as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Write != null)
            {
                var writeStringValue = Write.ToString();
                dictionary.Add("write", writeStringValue);
            }
            
            if (Read != null)
            {
                var readStringValue = Read.ToString();
                dictionary.Add("read", readStringValue);
            }
            
            if (Expires != null)
            {
                var expiresStringValue = Expires.ToString();
                dictionary.Add("expires", expiresStringValue);
            }
            
            var maxSizeStringValue = MaxSize.ToString();
            dictionary.Add("maxSize", maxSizeStringValue);
            
            return dictionary;
        }
    }
}
