#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Services.Multiplayer.Editor.Matchmaker.Authoring.AdminApi;

namespace Unity.Services.Multiplayer.Editor.Matchmaker.Authoring.AdminApi.Matchmaker.Model
{
    /// <summary>
    /// CloudCodeHostingConfig
    /// </summary>
    [DataContract(Name = "CloudCodeHostingConfig")]
    [Preserve]
    partial class CloudCodeHostingConfig
    {
        /// <summary>
        /// The type of hosting. Must be \&quot;CloudCode\&quot;.
        /// </summary>
        /// <value>The type of hosting. Must be \&quot;CloudCode\&quot;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum CloudCode for value: CloudCode
            /// </summary>
            [EnumMember(Value = "CloudCode")]
            CloudCode = 1

        }

        /// <summary>
        /// The type of hosting. Must be \&quot;CloudCode\&quot;.
        /// </summary>
        /// <value>The type of hosting. Must be \&quot;CloudCode\&quot;.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [Preserve]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// The name of the Cloud Code module.
        /// </summary>
        /// <value>The name of the Cloud Code module.</value>
        [DataMember(Name = "moduleName", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string ModuleName { get; set; }

        /// <summary>
        /// The name of the Cloud Code function that performs server allocation.
        /// </summary>
        /// <value>The name of the Cloud Code function that performs server allocation.</value>
        [DataMember(Name = "allocateFunctionName", EmitDefaultValue = false)]
        [Preserve]
        public string AllocateFunctionName { get; set; }

        /// <summary>
        /// The name of the Cloud Code function that performs polling of the server allocation.
        /// </summary>
        /// <value>The name of the Cloud Code function that performs polling of the server allocation.</value>
        [DataMember(Name = "pollFunctionName", EmitDefaultValue = false)]
        [Preserve]
        public string PollFunctionName { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CloudCodeHostingConfig" /> class.
        /// </summary>
        /// <param name="type">The type of hosting. Must be \&quot;CloudCode\&quot;..</param>
        /// <param name="moduleName">The name of the Cloud Code module. (required).</param>
        /// <param name="allocateFunctionName">The name of the Cloud Code function that performs server allocation..</param>
        /// <param name="pollFunctionName">The name of the Cloud Code function that performs polling of the server allocation..</param>
        [Preserve]
        public CloudCodeHostingConfig(TypeEnum? type = default(TypeEnum?), string moduleName = default(string), string allocateFunctionName = default(string), string pollFunctionName = default(string))
        {
            if (moduleName == null)
            {
                throw new ArgumentNullException("moduleName is a required property for CloudCodeHostingConfig and cannot be null");
            }
            this.ModuleName = moduleName;
            this.Type = type;
            this.AllocateFunctionName = allocateFunctionName;
            this.PollFunctionName = pollFunctionName;
        }
    }

}
#endif
